---
- name: Create ~/.Xresources
  command: touch ~/.Xresources
  args:
    creates: ~/.Xresources
- name: Xresources includes for urxvt
  lineinfile:
    state: present
    line: '#include ".Xresources.d/rxvt-unicode"'
    dest: '~/.Xresources'
- name: Xresources includes for rofi
  lineinfile:
    state: present
    line: '#include ".Xresources.d/rofi"'
    dest: '~/.Xresources'
