---
# - name: Install theme packages
#   yaourt:
#     name: "{{item}}"
#     state: present
#   with_items:
#     - vertex-icons-git
#     - gtk-theme-arc-git
- name: Set gtk-2.0 theme file
  file:
    src: "{{playbook_dir}}/roles/arch/files/home/.gtkrc-2.0"
    dest: "~/.gtkrc-2.0"
    state: link
