---
- name: Make dotfiles dirs
  file:
    state: directory
    path: "~/{{ item }}"
    recurse: yes
  with_items:
    - .config/bspwm
    - .config/dunst
    - .config/i3blocks
    - .config/i3
    - .config/herbstluftwm
    - .config/sxhkd
    - .config/vis/colors
    - .profile.d
    - .Xresources.d
- name: Symlink dotfiles
  file:
    src: "{{ playbook_dir }}/roles/arch/files/home/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items:
    - .compton.conf
    - .config/bspwm/bspwmrc
    - .config/bspwm/shell.sh
    - .config/desktop-background.jpeg
    - .config/dunst/dunstrc
    - .config/herbstluftwm/autostart
    - .config/herbstluftwm/panel.sh
    - .config/sxhkd/sxhkdrc
    - .config/sxhkd/toggle-mute.sh
    - .config/vis/config
    - .config/vis/colors/rainbow
    - .config/.xdg-config
    - .fehbg
    - .profile.d/arch-aliases.sh
    - .profile.d/arch-monitor.sh
    - .xinitrc
    # - .xprofile
    - .Xmodmap
    - .Xresources.d/rxvt-unicode
    - .Xresources.d/rofi
    - .zlogin
    - .yaourtrc

    - .config/i3/config
    - .config/i3/bogus.py
    - .config/i3/i3status.conf

    - .config/i3blocks/config
    - .config/i3blocks/i3blocks-contrib

- name: Create ~/.Xresources
  command: touch ~/.Xresources
  args:
    creates: ~/.Xresources
- name: Xresources includes for urxvt
  lineinfile:
    state: present
    line: '#include ".Xresources.d/rxvt-unicode"'
    dest: '~/.Xresources'
- name: Xresources includes for rofi
  lineinfile:
    state: present
    line: '#include ".Xresources.d/rofi"'
    dest: '~/.Xresources'
