---
- name: Make dotfiles dirs
  file:
    state: directory
    path: "~/{{ item }}"
    recurse: yes
  with_items:
    - .config/bspwm
    - .config/herbstluftwm
    - .config/sxhkd
    - .profile.d
    - .Xresources.d
- name: Symlink dotfiles
  file:
    src: "{{ playbook_dir }}/roles/arch/files/home/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items:
    - .compton.conf
    - .config/bspwm/bspwmrc
    - .config/bspwm/shell.sh
    - .config/desktop-background.jpeg
    - .config/herbstluftwm/autostart
    - .config/herbstluftwm/panel.sh
    - .config/sxhkd/sxhkdrc
    - .config/sxhkd/toggle-mute.sh
    - .config/.xdg-config
    - .fehbg
    - .profile.d/arch-aliases.sh
    - .profile.d/arch-monitor.sh
    - .xinitrc
    # - .xprofile
    - .Xmodmap
    - .Xresources.d/rxvt-unicode
    - .zlogin

- name: Xresources includes for urxvt
  lineinfile:
    state: present
    line: '#include ".Xresources.d/rxvt-unicode"'
    dest: '~/.Xresources'
