---
- include: sudo.yml
- include: dotfiles.yml
- include: packages.yml
- include: lightdm.yml
- include: theme.yml

- name: Disable pcspkr beep
  sudo: yes
  copy:
    src: "{{playbook_dir}}/roles/arch/files/etc/modprobe.d/nobeep.conf"
    dest: "/etc/modprobe.d/"
    owner: root
