---
- name: Install sudo
  pacman:
    name: sudo
    state: present
- name: Set sudoers file
  sudo: yes
  copy:
    src: "{{ playbook_dir }}/roles/arch/files/etc/sudoers"
    dest: /etc/sudoers
    owner: root
    mode: u=r,g=r
